repos:
  - repo: local
    hooks:
      - id: stagedfright
        name: stagedfright
        language: system
        entry: stagedfright .stagedfright
        verbose: true
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black
      language_version: python3
      types:
        - python
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
